apiVersion: v1
kind: PersistentVolume
metadata:
  name: deptrack-postgresql-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: deptrack-postgresql-volume
  local:
    path: /mnt/jenkins
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lfs262-k8s-master01
          - lfs262-k8s-worker01
          - lfs262-k8s-worker02
